### ISSUE TITLE
Feedback on the reCAPTCHA solver

### ISSUE THREAD

**Issue by Laululytia** [maximedrn/opensea-automatic-bulk-upload-and-sale#190] opened 2022-03-21 21:20 UTC
Login to Opensea problem solved! Thank you!!! 💯 But I have another one... 

Before script starts to upload NFTs:

![CA13D8C4-D9BE-4E61-BD29-A6873C63E0B7](https://user-images.githubusercontent.com/101800889/159365448-06de7599-d747-42bc-aba5-6b7fd213f457.jpeg)

Then Bot frozens when solving recaptcha in Opensea, after two minutes "I am not robot" window in Opensea dissapears and I have this one over and over again:

<img width="507" alt="Screenshot 2022-03-21 231509" src="https://user-images.githubusercontent.com/101800889/159365242-668c7497-5d27-4733-af76-722c13192f65.png">

- Operating system: Windows 64
- ChromeDriver - Google Chrome.
- Python version 3.9.9

Will be waiting for your answer, 450 of 2000 NFT uploaded manually :////

**Comment by Vural78** [comment] 2022-03-21 22:05
If the **crosswalk, chimneys or bridges** renew the captcha when they appear, the bot can continue to work with a captcha that it can solve.

It says "Solved" but doesn't actually solve it. That's why the upload fails.

The error I get is as follows:

`Login to MetaMask. Logged to MetaMask.
Login to OpenSea. Logged to OpenSea.

NFT n°1/5761:
Uploading NFT. Solving the reCAPTCHA. Solved.
Upload failed. Message:
Data saved in data/upload_and_sale_89fa71bc.csv

NFT n°2/5761:
Uploading NFT. Solving the reCAPTCHA. Solved.
Upload failed. Message:
Data saved in data/upload_and_sale_89fa71bc.csv`

**Comment by maximedrn** [comment] 2022-03-22 06:27
@Laululytia, what is your computer's graphic card?
Maybe Torch+CPU module do not work with Yolov5, I've to try because I'm using Torch+CUDA (`pip3 install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio===0.11.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html`)

@Vural78, I get this error sometimes, I've to check that. By the way what's your graphic card?

**Comment by Vural78** [comment] 2022-03-22 07:10
> @Laululytia, what is your computer's graphic card? Maybe Torch+CPU module do not work with Yolov5, I've to try because I'm using Torch+CUDA (`pip3 install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio===0.11.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html`)
> 
> @Vural78, I get this error sometimes, I've to check that. By the way what's your graphic card?

my graphics card model: nVidia GT 635M

**Comment by maximedrn** [comment] 2022-03-22 07:14
Can you tell me if your graphic card has CUDA:
https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#:~:text=You%20can%20verify%20that%20you,that%20GPU%20is%20CUDA%2Dcapable.
It seems that Torch uses CUDA or your CPU (but it needs to be powerful).

**Comment by Vural78** [comment] 2022-03-22 07:35
> Can you tell me if your graphic card has CUDA: https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#:~:text=You%20can%20verify%20that%20you,that%20GPU%20is%20CUDA%2Dcapable. It seems that Torch uses CUDA or your CPU (but it needs to be powerful).

My graphics card supports CUDA version 2.1

**Comment by maximedrn** [comment] 2022-03-22 07:39
Do you have an error with this command:
`pip install torch==1.11.0+cu113`

**Comment by Vural78** [comment] 2022-03-22 07:42
Yes, the error I get is as follows:

```
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement torch==1.11.0+cu113 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
ERROR: No matching distribution found for torch==1.11.0+cu113
```

**Comment by maximedrn** [comment] 2022-03-22 07:46
Are you using Python 3.9.7, 3.9.9 or 3.9.11 ?
`python --version`
If it really doesn't work, just type `pip install torch` with one of the Python version above. Your GPU doesn't have CUDA 11.3, it means that your PC may not solve recaptcha using image recognition :/

**Comment by Vural78** [comment] 2022-03-22 07:50
I am using Python 3.9.9
However, there is a CUDA driver on the nvidia site and it detected my system, I am installing it now. I'll try again when the download is complete.

**Comment by Vural78** [comment] 2022-03-22 08:05
I am really sad,
My system still gives the same error.

**Comment by maximedrn** [comment] 2022-03-22 08:06
CUDA 11.6 cannot be installed ? https://developer.nvidia.com/cuda-downloads

**Comment by Vural78** [comment] 2022-03-22 08:09
> CUDA 11.6 cannot be installed ? https://developer.nvidia.com/cuda-downloads

Install successfully. But I don't understand why it is not working.

**Comment by maximedrn** [comment] 2022-03-22 08:09
Can you show me the error?

**Comment by Vural78** [comment] 2022-03-22 08:15
[https://www.linkpicture.com/q/error_5.png](https://www.linkpicture.com/q/error_5.png)

**Comment by maximedrn** [comment] 2022-03-22 08:16
Try this:
```
pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio===0.11.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```
I'm fixing this issue with the requirements file.. I don't know why it only works using this command.

**Comment by Vural78** [comment] 2022-03-22 08:19
Yes, it seems to happen. currently downloading 2.2 GB file

**Comment by Vural78** [comment] 2022-03-22 08:22
[![image](https://www.linkpicture.com/q/asd_10.png)](https://www.linkpicture.com/view.php?img=LPic623986e5dd0bf1527571307)

**Comment by Vural78** [comment] 2022-03-22 08:33
I think my CUDA version is 9.1.84
And still trying to solve it using CPU power.

[![image](https://www.linkpicture.com/q/33_21.png)](https://www.linkpicture.com/view.php?img=LPic6239892b6426f135988493)
[![image](https://www.linkpicture.com/q/44_2.png)](https://www.linkpicture.com/view.php?img=LPic6239892b6426f135988493)

**Comment by maximedrn** [comment] 2022-03-22 08:35
Open a command prompt and type `nvidia-smi`. It should display the CUDA version.

**Comment by Vural78** [comment] 2022-03-22 09:14
Pictures as below.
When I click on the link it allows download and even installation.
I consider myself very unlucky.

[![image](https://www.linkpicture.com/q/1_1181.png)](https://www.linkpicture.com/view.php?img=LPic623992c0df24f872817903)
[![image](https://www.linkpicture.com/q/2_1827.png)](https://www.linkpicture.com/view.php?img=LPic623992c0df24f872817903)
[![image](https://www.linkpicture.com/q/3_1142.png)](https://www.linkpicture.com/view.php?img=LPic623992c0df24f872817903)

**Comment by maximedrn** [comment] 2022-03-22 09:40
This is the Python 3.7 version of PyTorch that uses CUDA 9: https://download.pytorch.org/whl/cu90/torch-1.0.0-cp37-cp37m-win_amd64.whl
You can download it and try to install the whl file using `pip install torch-1.0.0-cp37-cp37m-win_amd64.whl`
I hope it will work :/

**Comment by Vural78** [comment] 2022-03-22 09:43
I will try. I hope it works. Thank you for your supports.

**Comment by Kisnobeats** [comment] 2022-03-22 11:40
Running same Python as the dev, CUDA 11.6, and installed all that was required. Ran "main.py" and this is what came up..

"C:\Users\Kisnobeats\.wdm\drivers\chromedriver\win32\99.0.4844.51\chromedriver.exe
An error occured while loading Yolov5 and RealESRGAN.
Please verify that your computer is enough powerful,
every modules are installed and files presents in the directory.
No module named 'matplotlib'"

I've tried on my MSI gaming laptop, and currently just tried on my custom desktop. I will try again on my wife's computer since it is fairly new.

**Comment by Sequento** [comment] 2022-03-22 13:58
> Running same Python as the dev, CUDA 11.6, and installed all that was required. Ran "main.py" and this is what came up..
> 
> "C:\Users\Kisnobeats.wdm\drivers\chromedriver\win32\99.0.4844.51\chromedriver.exe An error occured while loading Yolov5 and RealESRGAN. Please verify that your computer is enough powerful, every modules are installed and files presents in the directory. No module named 'matplotlib'"
> 
> I've tried on my MSI gaming laptop, and currently just tried on my custom desktop. I will try again on my wife's computer since it is fairly new.

From upload folder, just use in cmd. - pip install matplotlib

**Comment by maximedrn** [comment] 2022-03-22 14:03
It comes from the requirements file. I'm working on this because some modules have conflict.

**Comment by Sequento** [comment] 2022-03-22 14:06
> It comes from the requirements file. I'm working on this because some modules have conflict.

thanks! because from the  pip install requirements are not installed from the file txt, I had to install all the modules manually

**Comment by maximedrn** [comment] 2022-03-22 14:08
Numpy has some conflict. I'm now trying on Python 3.10 - it works on 3.9.9.

**Comment by maximedrn** [comment] 2022-03-22 17:20
I have updated the requirements file and released version 1.6.1.
It seems that the necessary modules are present and that there is no conflict.

**Comment by jadedtakesthiscereal** [comment] 2022-03-22 17:29
my pc is too slow to run the newest recaptcha solving code.. my cuda maxes at 3.0 not the needed 3.7..  is there a way to run this in google colab.. i tried but got keyerror display.

**Comment by maximedrn** [comment] 2022-03-22 17:34
Can you show me the error?
Maybe Google Colab allows Selenium executable, it may work.

**Comment by jadedtakesthiscereal** [comment] 2022-03-22 17:53
![code i use](https://user-images.githubusercontent.com/102177219/159544375-6863faf7-45c2-4494-96ad-3108555caa00.png)
![ss colab](https://user-images.githubusercontent.com/102177219/159544419-4bb8e8eb-096b-4439-9551-fbb40dd8c1e1.png)

**Comment by maximedrn** [comment] 2022-03-22 19:04
It tries to get the display from the environ but this key doesn't exist. I don't if it's caused by Colaboratory environnement (Jupyter Notebook, no screen because it's a Linux command line), or just an OS module error that can be fixed.

**Comment by jadedtakesthiscereal** [comment] 2022-03-22 19:14
I had found that same article but was not sure if you had already found a workaround.  That is where I started to look for running chromedriver in there since the browser is like a display, but with no luck.  Thank you for replying so fast.  I very much appreciate your help and code.  I am still using your older code with the 2 min manual recaps, and used the build before it very enjoyably.  The opensea Captchas are tedious but it still beats typing all that metadata info like properties manually.  I will be dropping some eth to your wallet if I make any money.  opensea.io/collection/animalbudsnft 1650 of 10k loaded,,, back to the grind

**Comment by maximedrn** [comment] 2022-03-22 19:19
I will do some research on Google Colab. I think it is possible to run my bot on this platform

**Comment by kais1978** [comment] 2022-03-22 19:40
@maximedrn is there a way to do the recaptcha manually while the bot does all the other actions. My laptop is so slow that it takes forever after i finish the recaptcha manually for it to proceed.

**Comment by Laululytia** [comment] 2022-03-22 20:48
> @maximedrn is there a way to do the recaptcha manually while the bot does all the other actions. My laptop is so slow that it takes forever after i finish the recaptcha manually for it to proceed. I have macbook air 2017 edition

You can do it manually while script runs itself. I have tried upload + sell,  when recaptcha appears you just solve it yourself. Then bot runs properly. And it takes about one minute to list 1 NFT, but it makes me crazy to solve manually...

**Comment by maximedrn** [comment] 2022-03-23 11:59
> @maximedrn is there a way to do the recaptcha manually while the bot does all the other actions. My laptop is so slow that it takes forever after i finish the recaptcha manually for it to proceed. I have macbook air 2017 edition

I'll upload a version to do it manually :)

**Comment by Laululytia** [comment] 2022-03-23 13:19
> main-manual-resolution.py

Amazing! Works perfectly, thank you!!! 1 Nft upload + sale in 60 sec 💯💯💯💯💯

**Comment by kais1978** [comment] 2022-03-23 13:41
I have already installed the requirement file already. Now, when I want to install any of the 2 files you mentioned here, it says file not found. The bot is working perfectly fine with me until it reaches solving recaptcha, it gets stuck, I do it manually and I have to wait for about 3 minutes until the bot lists the nft for sale. I think it is a problem with the graphics card on my mac which is Intel HD Graphics 6000 1536 MB. I installed the file "pip install torch torchvision torchaudio" as I'm not sure of the CUDA and how t check it. Did I do anything wrong?

**Comment by maximedrn** [comment] 2022-03-23 13:49
> I have already installed the requirement file already. Now, when I want to install any of the 2 files you mentioned here, it says file not found. The bot is working perfectly fine with me until it reaches solving recaptcha, it gets stuck, I do it manually and I have to wait for about 3 minutes until the bot lists the nft for sale. I think it is a problem with the graphics card on my mac which is Intel HD Graphics 6000 1536 MB. I installed the file "pip install torch torchvision torchaudio" as I'm not sure of the CUDA and how t check it. Did I do anything wrong?

Newly added files should be placed in the repository directory.
Your graphics card does not have CUDA (only for Nvidia GPUs), maybe your processor is powerful enough if it is a recent Mac (M1 or M1 Max).

**Comment by kais1978** [comment] 2022-03-24 17:34
python main-manual-resolution.py
  File "main-manual-resolution.py", line 2
SyntaxError: Non-ASCII character '\xc3' in file main-manual-resolution.py on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Any idea how to fix this?

**Comment by maximedrn** [comment] 2022-03-24 17:51
> python main-manual-resolution.py File "main-manual-resolution.py", line 2 SyntaxError: Non-ASCII character '\xc3' in file main-manual-resolution.py on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details Any idea how to fix this?

What version of Python are you using?

**Comment by maximedrn** [comment] 2022-03-24 18:01
> 3.9

Remove lines 1 to 16, it should work.

**Comment by kais1978** [comment] 2022-03-24 18:10
How can I do that plz? Still learning, sorry

**Comment by jadedtakesthiscereal** [comment] 2022-03-24 19:03
kais1978 usually it's as easy as opening the code in whatever editor ya like.  I think they just mean open the main-manual-resolution.py file with any editor, notepad++ should work.  delete lines 1-16 literally, save and try the processs again like normal.    make sure you save a copy of your original file in a safe place though incase ya make somethin worse.

**Comment by jadedtakesthiscereal** [comment] 2022-03-24 19:09
maxime - between trying to find a way to run this on colab and using the previous versions to continue loading (1930 of 10k) I tried the torch installs you mentioned in this feedback to use cpu but I get this error, anything I can do that you are aware of
![error](https://user-images.githubusercontent.com/102177219/159992396-4f692397-5447-4e0e-a805-ba2790ce0584.png)

**Comment by maximedrn** [comment] 2022-03-24 19:17
> maxime - between trying to find a way to run this on colab and using the previous versions to continue loading (1930 of 10k) I tried the torch installs you mentioned in this feedback to use cpu but I get this error, anything I can do that you are aware of ![error](https://user-images.githubusercontent.com/102177219/159992396-4f692397-5447-4e0e-a805-ba2790ce0584.png)

It tries to use CUDA, it seems that you installed Torch+CUDA.

I did some testing on Google Colab, it works perfectly except for the OpenSea login - I'm blocked by Cloudflare. I haven't tried the reCAPTCHA solution but it should work.
I'll try to find a solution for Cloudflare if it's possible.

For now, you can use the manual file (`main-manual-resolution.py`, upgrade your computer or use a paid service (you have to modify the code).

**Comment by jadedtakesthiscereal** [comment] 2022-03-24 19:28
Cloudflare ddos blocker is my only other pain point besides recaptcha.  Vpn is usually how I get beyond that but colabs environment likely stops that.  It would be amazing for the people without good gpu to use.  Thank you for looking into it.  - as for last question specifics, can I unistall the torch cuda to try using cpu? Is the uninstall all needed to retry if that is an option or do i then reinstall specific items

**Comment by maximedrn** [comment] 2022-03-24 19:33
> Cloudflare ddos blocker is my only other pain point besides recaptcha. Vpn is usually how I get beyond that but colabs environment likely stops that. It would be amazing for the people without good gpu to use. Thank you for looking into it. - as for last question specifics, can I unistall the torch cuda to try using cpu? Is the uninstall all needed to retry if that is an option or do i then reinstall specific items

Uninstall torch, torchvision and torchaudio using:
`pip uninstall torch torchvision torchaudio`,
and then reinstall torch using:
`pip install torch torchvision torchaudio`.
It should now use your CPU.

**Comment by jadedtakesthiscereal** [comment] 2022-03-24 19:54
Works, pc tried a few times but not fast enough.  Using main-manual-resolution successfully though.  Thank You

**Comment by Joseph-Z** [comment] 2022-03-24 21:43
My computer is GTX2080, I9, with CUDA11.6 and torch, but I still can't read the captcha

**Comment by kingchenc** [comment] 2022-03-25 13:23
I just Testing the Captcha Solver, Upload Error so far ignoring....
i'm using headless firefox mode

1. Captcha Solved in 5 Seconds
2. Captcha Script Crashed 



NFT n°1/6:
Uploading NFT. Solving the reCAPTCHA. Solved.
Upload failed. Message:
Data saved in data/upload_e8a90899.csv

NFT n°2/6:
Uploading NFT. Solving the reCAPTCHA. Upload failed. Message: Cannot solve the reCAPTCHA.
Traceback (most recent call last):
  File "C:\Opensea\recaptcha.py", line 266, in proceed
    self.select_blocks()  # Check blocks and new blocks.
  File "C:\Opensea\recaptcha.py", line 236, in select_blocks
    if result[block]:  # Result is True, element has to be clicked.
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Opensea\main.py", line 602, in upload
    gateway.proceed()
  File "C:\Opensea\recaptcha.py", line 300, in proceed
    solver.proceed()
  File "C:\Opensea\recaptcha.py", line 281, in proceed
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Opensea\main.py", line 605, in upload
    raise TE('Cannot solve the reCAPTCHA.')
selenium.common.exceptions.TimeoutException: Message: Cannot solve the reCAPTCHA.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Opensea\main.py", line 961, in <module>
    if opensea.upload() and 2 in action:
  File "C:\Opensea\main.py", line 619, in upload
    structure.save_upload() if 2 not in structure.action else \
  File "C:\Opensea\main.py", line 222, in save_upload
    self.save('upload', self.upload_details)
  File "C:\Opensea\main.py", line 214, in save
    with open(eval(f'self.{mode}_file'), 'a+', encoding='utf-8') as file:
PermissionError: [Errno 13] Permission denied: 'data/upload_e8a90899.csv'




the other error, whats that mean?
requirements: C:\Opensea\yolov5\requirements.txt not found, check failed.

**Comment by maximedrn** [comment] 2022-03-25 14:49
`requirements: C:\Opensea\yolov5\requirements.txt not found, check failed.`
Don't worry about this "error". I deleted some files from Yolov5 and Real-ESRGAN.

Then it doesn't crash because the reCAPTCHA failed, it crashes because of this:
`PermissionError: [Errno 13] Permission denied: 'data/upload_e8a90899.csv'``.
Try running your bot as administrator.

> Maybe reload Page and retry same nft after XY reload captcha and without skip to the next one.

I noticed this problem, the bot should normally try a second time to upload the NFT.

**Comment by maximedrn** [comment] 2022-03-26 09:56
> > `requirements: C:\Opensea\yolov5\requirements.txt not found, check failed.` Don't worry about this "error". I deleted some files from Yolov5 and Real-ESRGAN.
> > Then it doesn't crash because the reCAPTCHA failed, it crashes because of this: `PermissionError: [Errno 13] Permission denied: 'data/upload_e8a90899.csv'``. Try running your bot as administrator.
> > > Maybe reload Page and retry same nft after XY reload captcha and without skip to the next one.
> > 
> > 
> > I noticed this problem, the bot should normally try a second time to upload the NFT.
> 
> Yes i figured out that i must my cmd with Admin rights but thanks :)
> 
> Yes that would be good if you can add this with reload Page / Retry with XY trys :)

Retry if download and sale failed has been re-added :)

**Comment by jadedtakesthiscereal** [comment] 2022-03-26 17:10
using newest main-manual-resolution.py this morning
![error326](https://user-images.githubusercontent.com/102177219/160250129-0b5f9d44-a1ba-44ee-ab63-be0cb72bfab4.png)

**Comment by jadedtakesthiscereal** [comment] 2022-03-26 17:36
Ps - opensea put 6month listing back on the clickables without having to enter the specific date.. so changing duration in your metadata file from “1 month” to “6 months” does work-  using the newest load of main-manual-resolution.. the retry sale is working great

**Comment by maximedrn** [comment] 2022-03-26 17:39
> Ps - opensea put 6month listing back on the clickables without having to enter the specific date.. so changing duration in your metadata file from “1 month” to “6 months” does work

I agree 👍. The bot doesn't have a filter on this duration format.
You can enter whatever you want as long as OpenSea offers it in the dropdown.

**Comment by maximedrn** [comment] 2022-03-27 16:38
I'm closing this issue. Everything seems to be clear about the reCAPTCHA now :)
Feel free to reopen or open a question with the same name as this one to ask questions or talk about problems you've encountered.

**Closed by maximedrn** 2022-03-27 16:38 UTC

**Comment by maximedrn** [comment] 2022-10-11 08:24
It tries to get the display from the environ but this key doesn't exist. I don't if it's caused by Colaboratory environnement (Jupyter Notebook, no screen because it's a Linux command line), or just an OS module error that can be fixed.
-------- Message d'origine --------De : jadedtakesthiscereal ***@***.***> Date : 22/03/2022  19:42  (GMT+01:00) À : maximedrn/opensea-automatic-bulk-upload-and-sale ***@***.***> Cc : Maxime Dréan ***@***.***>, Assign ***@***.***> Objet : Re: [maximedrn/opensea-automatic-bulk-upload-and-sale] Feedback on
  the reCAPTCHA solver #2 (Issue #190) 
here is what happens when i upload all files into colab,  run pip requirements install then  main.py
