### ISSUE TITLE
Captcha!!!

### ISSUE THREAD

**Issue by nabeelsaleem** [maximedrn/opensea-automatic-bulk-upload-and-sale#117] opened 2022-02-18 19:28 UTC
Is it still working?
I am seeing captcha,

![image](https://user-images.githubusercontent.com/6704727/154749012-1b5d798e-3cb6-45f2-bda1-80c2a99a9950.png)

is there any way to bypass captchas?
used best chrome extensions but no luck.

**Comment by maximedrn** [comment] 2022-02-18 20:03
With the lastest version?

**Comment by nabeelsaleem** [comment] 2022-02-19 09:02
> With the lastest version?

Didn't try latest version, 
Did you add the solution in it?

**Comment by nabeelsaleem** [comment] 2022-02-19 09:41
i have 500 pngs, do i need to write 500 lines here?

![image](https://user-images.githubusercontent.com/6704727/154795539-fa90a931-de1a-4ddf-afc8-b3824aeb1be8.png)


Also can you guide a little how to automatically increase numbers instead of adding one by one in this xlsx file.

**Comment by maximedrn** [comment] 2022-02-19 10:14
Since version 1.5.0, the reCAPTCHAs are bypassed.
Excel offers ways to increment.

**Comment by Ken5998** [comment] 2022-02-19 13:03
> i have 500 pngs, do i need to write 500 lines here?
> 
> ![image](https://user-images.githubusercontent.com/6704727/154795539-fa90a931-de1a-4ddf-afc8-b3824aeb1be8.png)
> 
> Also can you guide a little how to automatically increase numbers instead of adding one by one in this xlsx file.

I have used this guide: https://www.excelhow.net/how-to-create-increment-number-with-texts-in-excel.html#:~:text=Please%20see%20below%20steps%20for,column%20A%20to%20two%20parts.&text=Step%202%3A%20Select%20the%20range,E2%20enter%20the%20formula%20%3DC2%26D2.

**Comment by berkaytscc** [comment] 2022-02-19 13:12
@Ken5998 Well I don't know exactly but I can tell you the way I do it. I first integrated the metadata for @maximedrn's format. Then created the png files with metadata.

**Comment by berkaytscc** [comment] 2022-02-19 13:13
@nabeelsaleem Captcha is fixed. I can ensure that.

**Comment by maximedrn** [comment] 2022-02-19 13:24
The most time consuming part is to create the metadata file. You can use Python (or other languages like VBS integrated to Excel) to make it easier.

**Comment by nabeelsaleem** [comment] 2022-02-19 13:39
Thank you both,
i have managed with this formula.

`="C:/Users/Nabeel/Desktop/nfts1-501/images/"&ROWS(C$7:C7)&".png"
`
![image](https://user-images.githubusercontent.com/6704727/154803155-615a6c96-3f06-460f-83a6-90c71e8f215e.png)

**Comment by nabeelsaleem** [comment] 2022-02-19 15:25
What is this????
why asking these secret phrase?

![image](https://user-images.githubusercontent.com/6704727/154807229-be2468fa-9fd4-4e65-a497-560076d66984.png)

**Comment by nabeelsaleem** [comment] 2022-02-19 15:27
> What is this???? why asking these secret phrase?
> 
> ![image](https://user-images.githubusercontent.com/6704727/154807229-be2468fa-9fd4-4e65-a497-560076d66984.png)

![image](https://user-images.githubusercontent.com/6704727/154807366-3dd78714-bb99-48d4-828e-1de9d640ee90.png)

**Comment by maximedrn** [comment] 2022-02-19 15:29
Your recovery phrase is only used to connect to the MetaMask extension. I don't have access to anything.

**Comment by nabeelsaleem** [comment] 2022-02-19 15:51
This should be like this:
your script open browse and then browser metamask ask to login.

It looks risky right now

**Comment by maximedrn** [comment] 2022-02-19 16:47
The problem is that the connection is made for each upload. So asking to connect each time is long.
Don't worry, everything is secure, it's like if you connect to the extension for the very first time and then you decide to upload an NFT to OpenSea. The advantage is that everything is done automatically with the help of a browser automation.

**Comment by maximedrn** [comment] 2022-02-19 16:48
But obviously, don't give anyone your recovery phrase. This bot is nobody, it's just you, your PC and a connection.

**Comment by maximedrn** [comment] 2022-02-19 17:49
I close this issue.

**Closed by maximedrn** 2022-02-19 17:49 UTC
Labels: bug

**Comment by nabeelsaleem** [comment] 2022-02-19 17:51
Ok.

received error here

![image](https://user-images.githubusercontent.com/6704727/154812809-26ad116c-d83e-4ba4-981f-5674ee242dc5.png)

**Comment by maximedrn** [comment] 2022-02-19 17:52
```
pip install openpyxl
```

**Comment by nabeelsaleem** [comment] 2022-02-19 18:01
@maximedrn really sorry for too much questions. 

Please check this. I have added one excel file in data folder with all required fields, non required are empty.

![image](https://user-images.githubusercontent.com/6704727/154813109-ff3498b1-b2e2-4e48-9301-9ce56ef2d7e4.png)

![image](https://user-images.githubusercontent.com/6704727/154813144-a24f2802-95e8-4807-b4d1-6a202d21ea27.png)

**Comment by maximedrn** [comment] 2022-02-19 18:26
It's very simple, the duration must be specified like this:
["DD-MM-YYYY hh:mm", "DD-MM-YYYY hh:mm"] (example: ["19-02-2022 20:10", "19-05-2022 21:14"] ) or:
["1 day"]
["3 days"]
["1 week"]
["1 month"]

**Comment by nabeelsaleem** [comment] 2022-02-19 21:24
> 

I tried all

["4 month"] is not working

["1 month"] is not working

also dates options not working. only dropdown options works

**Comment by nabeelsaleem** [comment] 2022-02-22 18:51
Hi,

It was working awesome, But today i face this captcha.

![image](https://user-images.githubusercontent.com/6704727/155199238-d7dd83f9-6f48-484f-a391-7e3f3c529bb6.png)

**Comment by maximedrn** [comment] 2022-02-22 19:03
Try it in a few hours.
OpenSea faces a massive traffic sometimes, you can see it on the first graph of this site: https://status.opensea.io/

**Comment by nabeelsaleem** [comment] 2022-02-22 19:05
> Try it in a few hours. OpenSea faces a massive traffic sometimes, you can see it on the first graph of this site: https://status.opensea.io/

Okay!
Thanks for this. Lets see in few hours :)
